// 30+ Indian art products for the new store
const indianArtProducts = [
  {
    id: 1,
    name: 'Madhubani Painting',
    price: 1299,
    description: 'Traditional Madhubani painting from Bihar, India.',
    image: '/assets/product_img1.png',
  },
  {
    id: 2,
    name: 'Rajasthani Miniature',
    price: 1599,
    description: 'Exquisite miniature painting from Rajasthan.',
    image: '/assets/product_img2.png',
  },
  {
    id: 3,
    name: 'Warli Art Panel',
    price: 999,
    description: 'Handcrafted Warli art panel from Maharashtra.',
    image: '/assets/product_img3.png',
  },
  {
    id: 4,
    name: 'Tanjore Painting',
    price: 2499,
    description: 'Classic Tanjore painting with gold foil work.',
    image: '/assets/product_img4.png',
  },
  {
    id: 5,
    name: 'Pattachitra Scroll',
    price: 1399,
    description: 'Odisha Pattachitra scroll painting.',
    image: '/assets/product_img5.png',
  },
  {
    id: 6,
    name: 'Phad Painting',
    price: 1199,
    description: 'Traditional Phad painting from Rajasthan.',
    image: '/assets/product_img6.png',
  },
  {
    id: 7,
    name: 'Kalamkari Wall Art',
    price: 1099,
    description: 'Hand-painted Kalamkari wall art.',
    image: '/assets/product_img7.png',
  },
  {
    id: 8,
    name: 'Cheriyal Scroll',
    price: 999,
    description: 'Colorful Cheriyal scroll painting from Telangana.',
    image: '/assets/product_img8.png',
  },
  {
    id: 9,
    name: 'Bengal Patachitra',
    price: 899,
    description: 'Bengal folk art Patachitra painting.',
    image: '/assets/product_img9.png',
  },
  {
    id: 10,
    name: 'Kerala Mural',
    price: 1799,
    description: 'Vibrant Kerala mural painting.',
    image: '/assets/product_img10.png',
  },
  {
    id: 11,
    name: 'Sikki Grass Craft',
    price: 799,
    description: 'Handcrafted Sikki grass art from Bihar.',
    image: '/assets/product_img11.png',
  },
  {
    id: 12,
    name: 'Gond Art Canvas',
    price: 1199,
    description: 'Gond tribal art on canvas.',
    image: '/assets/product_img12.png',
  },
  {
    id: 13,
    name: 'Bastar Metal Sculpture',
    price: 2499,
    description: 'Dhokra metal sculpture from Bastar.',
    image: '/assets/product_img13.png',
  },
  {
    id: 14,
    name: 'Jaipur Blue Pottery',
    price: 699,
    description: 'Handcrafted blue pottery from Jaipur.',
    image: '/assets/product_img14.png',
  },
  {
    id: 15,
    name: 'Banarasi Silk Painting',
    price: 1599,
    description: 'Banarasi silk painting with gold thread.',
    image: '/assets/product_img15.png',
  },
  {
    id: 16,
    name: 'Ajanta Cave Replica',
    price: 2999,
    description: 'Replica of Ajanta cave painting.',
    image: '/assets/product_img16.png',
  },
  // ...add more products up to 30+
];

export default indianArtProducts;
